In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
real_estate_data = pd.read_csv('/content/drive/MyDrive/dataset/uae_properties.csv')
real_estate_data.head()

,id,title,displayAddress,bathrooms,bedrooms,addedOn,type,rera,propertyType,price
0,10837871,★ EXCLUSIVE RELEASE ★ | LUXURY 3 BED FLAT | GO...,"Sobha One, Sobha Hartland, Mohammed Bin Rashid...",2,3,2024-01-06T17:05:24+00:00,buy,8.171857e+08,apartment,3950000
1,10880180,"★ BUY NOW 624,000AED ★ (20% FIRST PAYMENT + 4%...","Sobha Verde, Jumeirah Lake Towers, Dubai",2,3,2024-01-13T21:19:31+00:00,buy,8.171857e+08,apartment,2600000
2,11220200,GREEN HEART OF DUBAI |URBAN DESIGN | LUXURY LI...,"Park Horizon, Dubai Hills Estate, Dubai",2,3,2024-03-12T03:18:54+00:00,buy,2.125966e+09,apartment,3450000
3,11176502,Prime Location | Corner Spacious Unit | Bright...,"AZIZI Riviera, Meydan One, Meydan, Dubai",2,3,2024-03-04T06:53:51+00:00,buy,7.114978e+10,apartment,2000000
4,11179908,Very Limited | Ideal For Investment | 40% Disc...,"Verdana, Dubai Investment Park, Dubai",2,0,2024-03-04T13:24:39+00:00,buy,4.652616e+08,apartment,284000

In [3]:
real_estate_data.isnull().sum()

id                  0
title               0
displayAddress      0
bathrooms           0
bedrooms            0
addedOn             0
type                0
rera              169
propertyType        0
price               0
dtype: int64

In [4]:
real_estate_data = real_estate_data.drop(['addedOn','type','rera'],axis='columns')

In [5]:
real_estate_data.iloc[8]

id                                                         11115936
title                      Well Kept | Marina View | Prime Location
displayAddress    Marina Wharf 2, Marina Wharf, Dubai Marina, Dubai
bathrooms                                                         2
bedrooms                                                          3
propertyType                                              apartment
price                                                       1950000
Name: 8, dtype: object

In [6]:
real_estate_data.head()

,id,title,displayAddress,bathrooms,bedrooms,propertyType,price
0,10837871,★ EXCLUSIVE RELEASE ★ | LUXURY 3 BED FLAT | GO...,"Sobha One, Sobha Hartland, Mohammed Bin Rashid...",2,3,apartment,3950000
1,10880180,"★ BUY NOW 624,000AED ★ (20% FIRST PAYMENT + 4%...","Sobha Verde, Jumeirah Lake Towers, Dubai",2,3,apartment,2600000
2,11220200,GREEN HEART OF DUBAI |URBAN DESIGN | LUXURY LI...,"Park Horizon, Dubai Hills Estate, Dubai",2,3,apartment,3450000
3,11176502,Prime Location | Corner Spacious Unit | Bright...,"AZIZI Riviera, Meydan One, Meydan, Dubai",2,3,apartment,2000000
4,11179908,Very Limited | Ideal For Investment | 40% Disc...,"Verdana, Dubai Investment Park, Dubai",2,0,apartment,284000

In [7]:
original_data = real_estate_data.copy()

In [8]:
original_data.head()

,id,title,displayAddress,bathrooms,bedrooms,propertyType,price
0,10837871,★ EXCLUSIVE RELEASE ★ | LUXURY 3 BED FLAT | GO...,"Sobha One, Sobha Hartland, Mohammed Bin Rashid...",2,3,apartment,3950000
1,10880180,"★ BUY NOW 624,000AED ★ (20% FIRST PAYMENT + 4%...","Sobha Verde, Jumeirah Lake Towers, Dubai",2,3,apartment,2600000
2,11220200,GREEN HEART OF DUBAI |URBAN DESIGN | LUXURY LI...,"Park Horizon, Dubai Hills Estate, Dubai",2,3,apartment,3450000
3,11176502,Prime Location | Corner Spacious Unit | Bright...,"AZIZI Riviera, Meydan One, Meydan, Dubai",2,3,apartment,2000000
4,11179908,Very Limited | Ideal For Investment | 40% Disc...,"Verdana, Dubai Investment Park, Dubai",2,0,apartment,284000

In [9]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(real_estate_data['displayAddress']).toarray()
tfidf = pd.DataFrame(tfidf_matrix, columns=tfidf_vectorizer.get_feature_names_out())
tfidf.head()

,12,13,14,19,1a,1wood,20,22,2b,310,...,waters,waves,wharf,world,yakout,yas,yasmin,zahia,zahra,zenith
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
label_encoder = LabelEncoder()
real_estate_data['propertyType'] = label_encoder.fit_transform(real_estate_data['propertyType'])

In [11]:
scaler = MinMaxScaler()
real_estate_data[['bathrooms', 'bedrooms', 'price']] = scaler.fit_transform(real_estate_data[['bathrooms', 'bedrooms', 'price']])

In [12]:
numerical_features = real_estate_data[['bathrooms', 'bedrooms', 'propertyType', 'price']]
numerical_features.head()

   bathrooms  bedrooms  propertyType     price
0        0.0       1.0             0  0.260531
1        0.0       1.0             0  0.165907
2        0.0       1.0             0  0.225485
3        0.0       1.0             0  0.123852
4        0.0       0.0             0  0.003575

In [13]:
combined_features = pd.concat([pd.DataFrame(tfidf), pd.DataFrame(numerical_features)], axis=1)
combined_features.shape

(492, 369)

In [14]:
combined_features.head()

,12,13,14,19,1a,1wood,20,22,2b,310,...,yakout,yas,yasmin,zahia,zahra,zenith,bathrooms,bedrooms,propertyType,price
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,0.260531
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,0.165907
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,0.225485
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,0.123852
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.003575

In [15]:
cosine_sim = cosine_similarity(combined_features)

In [16]:
original_data.iloc[5]

id                                                        10860296
title             Burj And Fountain View | 5 Year PHPP I 3 Service
displayAddress               Forte 1, Forte, Downtown Dubai, Dubai
bathrooms                                                        2
bedrooms                                                         3
propertyType                                             apartment
price                                                      5000000
Name: 5, dtype: object

In [17]:
def get_recommendations(property_index):
    similarity_scores = list(enumerate(cosine_sim[property_index]))
    similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)
    top_n = 5
    top_properties = [i[0] for i in similarity_scores[1:top_n + 1]]
    recommendations = real_estate_data.iloc[top_properties]

    recommendations['propertyType'] = label_encoder.inverse_transform(recommendations['propertyType'])
    recommendations[['bathrooms', 'bedrooms', 'price']] = scaler.inverse_transform(recommendations[['bathrooms', 'bedrooms', 'price']])
    return recommendations

recommended_properties = get_recommendations(155)

print(original_data.loc[recommended_properties.index, ['id', 'title', 'displayAddress', 'bathrooms', 'bedrooms', 'propertyType', 'price']])

           id                                             title  \
58   11233649    Brand New I Mid Floor I Burj and Fountain View
5    10860296  Burj And Fountain View | 5 Year PHPP I 3 Service
166  11098181           Burj Khalifa View | High Floor | Vacant
165  11095496         Burj Khalifa View | High Floor | Tenanted
490  11151144  Full Burj Khalifa  | High Floor | Confirm Seller

                             displayAddress  bathrooms  bedrooms propertyType  \
58    Forte 1, Forte, Downtown Dubai, Dubai          2         3    apartment
5     Forte 1, Forte, Downtown Dubai, Dubai          2         3    apartment
166   Downtown Views, Downtown Dubai, Dubai          2         3    apartment
165   Downtown Views, Downtown Dubai, Dubai          2         3    apartment
490  Boulevard Point, Downtown Dubai, Dubai          2         3    apartment

       price
58   4800000
5    5000000
166  6500000
165  6300000
490  6600000

/tmp/ipython-input-17-651214751.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  recommendations['propertyType'] = label_encoder.inverse_transform(recommendations['propertyType'])
/tmp/ipython-input-17-651214751.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  recommendations[['bathrooms', 'bedrooms', 'price']] = scaler.inverse_transform(recommendations[['bathrooms', 'bedrooms', 'price']])

# Recommendation system

In [18]:
def recommend_by_input(displayAddress, bathrooms, bedrooms, propertyType, price):
    input_tfidf = tfidf_vectorizer.transform([displayAddress]).toarray()

    encoded_property_type = label_encoder.transform([propertyType])[0]

    scaled_features = scaler.transform([[bathrooms, bedrooms, price]])[0]

    input_vector = list(input_tfidf[0]) + list(scaled_features[:2]) + [encoded_property_type] + [scaled_features[2]]
    input_vector_df = pd.DataFrame([input_vector])

    similarities = cosine_similarity(input_vector_df, combined_features).flatten()

    top_indices = similarities.argsort()[::-1][1:6]
    recommendations = real_estate_data.iloc[top_indices]

    recommendations['propertyType'] = label_encoder.inverse_transform(recommendations['propertyType'])
    recommendations[['bathrooms', 'bedrooms', 'price']] = scaler.inverse_transform(recommendations[['bathrooms', 'bedrooms', 'price']])

    return original_data.loc[recommendations.index, ['id', 'title', 'displayAddress', 'bathrooms', 'bedrooms', 'propertyType', 'price']]

In [20]:
recommended = recommend_by_input(
    displayAddress="Downtown Dubai",
    bathrooms=2,
    bedrooms=3,
    propertyType="apartment",
    price=2500000
)
print(recommended)

           id                                             title  \
166  11098181           Burj Khalifa View | High Floor | Vacant
490  11151144  Full Burj Khalifa  | High Floor | Confirm Seller
447  10306867            Stunning Burj Khalifa View | Exclusive
155  11236382     Bright and Elegant 3BR with Burj Khalifa View
58   11233649    Brand New I Mid Floor I Burj and Fountain View

                                    displayAddress  bathrooms  bedrooms  \
166          Downtown Views, Downtown Dubai, Dubai          2         3
490         Boulevard Point, Downtown Dubai, Dubai          2         3
447  The Address Dubai Mall, Downtown Dubai, Dubai          2         3
155          Forte 1, Forte, Downtown Dubai, Dubai          2         3
58           Forte 1, Forte, Downtown Dubai, Dubai          2         3

    propertyType     price
166    apartment   6500000
490    apartment   6600000
447    apartment  10000000
155    apartment   4500000
58     apartment   4800000

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
/tmp/ipython-input-18-2917378714.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  recommendations['propertyType'] = label_encoder.inverse_transform(recommendations['propertyType'])
/tmp/ipython-input-18-2917378714.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  recommendations[['bathrooms', 'bedrooms', 'price']] = scaler.inverse_transform(recommendations[['bathrooms', 'bedrooms', 'price']])

In [ ]:
# import pandas as pd
# from sklearn.preprocessing import LabelEncoder, MinMaxScaler
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.metrics.pairwise import cosine_similarity

# # Load the dataset
# real_estate_data = pd.read_csv('/content/drive/MyDrive/dataset/uae_properties.csv')

# # Drop unnecessary columns and handle NaN values
# real_estate_data = real_estate_data.drop(['type', 'rera', 'addedOn'], axis='columns')
# real_estate_data = real_estate_data.dropna()

# # Store original values
# original_data = real_estate_data.copy()

# # Preprocess the dataset
# tfidf_vectorizer = TfidfVectorizer()
# tfidf_matrix = tfidf_vectorizer.fit_transform(real_estate_data['displayAddress']).toarray()

# label_encoder = LabelEncoder()
# real_estate_data['propertyType'] = label_encoder.fit_transform(real_estate_data['propertyType'])

# scaler = MinMaxScaler()
# real_estate_data[['bathrooms', 'bedrooms', 'price']] = scaler.fit_transform(real_estate_data[['bathrooms', 'bedrooms', 'price']])

# numerical_features = real_estate_data[['bathrooms', 'bedrooms', 'propertyType', 'price']]
# combined_features = pd.concat([pd.DataFrame(tfidf_matrix), pd.DataFrame(numerical_features)], axis=1)

# similarity_matrix = cosine_similarity(combined_features)

# def get_recommendations(property_index):
#     similarity_scores = list(enumerate(similarity_matrix[property_index]))
#     similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)
#     top_n = 5
#     top_properties = [i[0] for i in similarity_scores[1:top_n + 1]]
#     recommendations = real_estate_data.iloc[top_properties]

#     # Map back the original values
#     recommendations['propertyType'] = label_encoder.inverse_transform(recommendations['propertyType'])
#     recommendations[['bathrooms', 'bedrooms', 'price']] = scaler.inverse_transform(recommendations[['bathrooms', 'bedrooms', 'price']])
#     return recommendations

# recommended_properties = get_recommendations(55)

# # Display the recommendations with original values
# print(original_data.loc[recommended_properties.index, ['id', 'title', 'displayAddress', 'bathrooms', 'bedrooms', 'propertyType', 'price']])